### PR TITLE
Fix/refactor classes

### LINKED ISSUE #3: Build Ingredient Class
As a developer, when I visit the ingredient class, I want to see a class that instantiates ingredient data, so that I can create ingredient instances from ingredient data.

Should have properties:
- [x] id
- [x] name
- [x] estimated cost
Possible Methods:
- [x] `calculateCost()` - return the cost of the individual ingredient in dollars (and cents?)

Test:
- [x] All class properties
- [x] All methods and updates to properties
- [x] Any helper methods you build out
- [x] Happy/sad path tests
- [x] Create own data to test
- [x] `calculateCost()` should return dollar (and cents?)

### PR DESCRIPTION
**Pull request by alexthompson207**
## Is this a fix or a feature?

This is a fix.

## What is the change?

See below.

## What does it fix?

Add a helper method to the recipe class, to clean-up our `returnIngredientNames()` and `calculateIngredientCost()` methods, 
and make SRP and DRY methods. Also deleted the method in the ingredient class, and added a test to the properties for ingredient class.

## Where should the reviewer start?

In the ingredient class, no more method. Also in the recipe class, start on line 10 with the `findIngredient()` method.

## How should this be tested?

Run npm test, all recipe and ingredient tests should pass!

### CODE REVIEW

File: src/recipe.js [hunk 1]
```diff
@@ -7,35 +7,30 @@ class Recipe {
     this.name = name;
     this.tags = tags;
   }
-  returnIngredientNames(ingredientData) {
+  findIngredients(ingredientData) {
     const recipeIngredients = [];
     this.ingredients.forEach((recipeIngredient) => {
```
Comment (elizhahn) [inline src/recipe.js]: remove parenthesis around recipeIngredient

**Review by elizhahn — CHANGES_REQUESTED** [review]
remove parenthesis around

File: src/recipe.js (hunk 1 above)
Comment (alexthompson207) [reply src/recipe.js]: Good catch. Fixed it and pushed it up!

**Review by elizhahn — APPROVED** [review]
